---
- name: Launch Job From Ansible Tower to AWX
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Launch Job
      tower_job_launch:
        job_template: "{{ AWX_JOB_TEMPLATE_NAME }}"
        inventory: "Cisco Lab Inventory"
        credential: "Demo Credential"

      register: job
    
    - name: Wait for job max 30s
      tower_job_wait:
        job_id: "{{ job.id }}"
        timeout: 30
      
      register: results

    - name: Print Job Results
      debug:
        msg: "AWX Job {{ results.id }} Status: {{ results.status }} Took: {{ results.elapsed }} seconds" 
...
