---
- name: Gather Cisco IOS/IOSXE Inventory Facts
  gather_facts: false
  hosts: all
  ansible_network_provider: ansible-network.cisco_ios
  ansible_connection: network_cli
  tasks:
  
    - name: Collect Facts
      ios_facts:
        gather_subset: 
          - "!config"
      register: facts

    - name: Print JSON
      debug:
              msg: "{{inventory_hostname}} has version {{ansible_net_version}}"

   
   
