---
- name: Reload Routers
  hosts: TELEMETRY_CPE
  connection: local
  gather_facts: false

  tasks:
    - name: Reload Routers
      ios_command:
        commands:
          - "wr"
          - "reload\n"
